In [1]:
import pandas
import math

pandas.set_option("display.precision", 12)

def sq_side(sq :float):
    val = math.sqrt(4 - sq)
    return 2 - val

def new_data(data: dict):
    new = {}
    new['lados'] = 2 * data['lados']
    new['lado_cuadrado'] = sq_side(data['lado_cuadrado'])
    new['lado'] = math.sqrt(new['lado_cuadrado'])
    new['perímetro'] = new['lados'] * new['lado']
    new['semiperímetro'] = new['perímetro'] / 2
    new['área_triángulo'] = new['lado'] * (1 - sq_side(new['lado_cuadrado']) / 2) / 2
    new['área_total'] = new['lados'] * new['área_triángulo']
    return new

first_area = 1 * (1 - sq_side(1) / 2) / 2

first_data = {'lados': 6,
              'lado_cuadrado': 1,
              'lado': 1,
              'perímetro': 6,
              'semiperímetro': 3,
              'área_triángulo': first_area,
              'área_total': 6 * first_area
              }

table = [first_data]

In [2]:
for i in range(10):
    table.append(new_data(table[-1]))

In [3]:
data = pandas.DataFrame.from_dict(table)

data.head(11)

,lados,lado_cuadrado,lado,perímetro,semiperímetro,área_triángulo,área_total
0,6,1.000000000000,1.000000000000,6.000000000000,3.000000000000,0.433012701892,2.598076211353
1,12,0.267949192431,0.517638090205,6.211657082460,3.105828541230,0.250000000000,3.000000000000
2,24,0.068148347422,0.261052384440,6.265257226562,3.132628613281,0.129409522551,3.105828541230
3,48,0.017110277252,0.130806258460,6.278700406094,3.139350203047,0.065263096110,3.132628613281
4,96,0.004282153523,0.065438165644,6.282063901781,3.141031950891,0.032701564615,3.139350203047
5,192,0.001070825047,0.032723463253,6.282904944571,3.141452472285,0.016359541411,3.141031950890
6,384,0.000267724181,0.016362279208,6.283115215823,3.141557607912,0.008180865813,3.141452472285
7,768,0.000066932165,0.008181208052,6.283167784298,3.141583892149,0.004090569802,3.141557607912
8,1536,0.000016733111,0.004090612582,6.283180926474,3.141590463237,0.002045302013,3.141583892157
9,3072,0.000004183282,0.002045307361,6.283184212086,3.141592106043,0.001022653146,3.141590463272
10,6144,0.000001045821,0.001022653814,6.283185033176,3.141592516588,0.000511326840,3.141592105895

In [4]:
data.to_csv('geo_circle.csv')